version: '3.9'
services:
  fastapi_server:
    container_name: fastapi_app
    build:
      context: .

#    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000'"
    ports:
      - "8000:8000"

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
        interval: 10s
        timeout: 5s
        retries: 5

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    env_file: .env


  celery_worker:
    container_name: celery_worker
#    restart: always
    # platform: linux/arm64/v8
    build: .
    command: "celery -A app.core.celery worker -l info"
    depends_on:
      - db
      - redis
    env_file: .env

  celery_beat:
    container_name: celery_beat
    restart: always
    # platform: linux/arm64/v8
    build: .
    command: "celery -A app.core.celery beat -l info"
    depends_on:
      - db
      - redis
    env_file: .env

  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker

volumes:
  postgres-data:
