[tool.ruff]
line-length = 119
exclude = [".git", "__pycache__", ".pytest_cache", "./Game"]
lint.select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "C",  # flake8-comprehensions
#    "I",  # isort
    "N",  # pep8-naming
    "UP",  # pyupgrade
    "YTT",  # flake8-2020
    "S",  # flake8-bandit security
    "BLE",  # flake8-blind-except
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "DTZ",  # flake8-datetimez
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "PIE",  # flake8-pie
    "PT",  # flake8-pytest-style
    "RSE",  # flake8-raise
    "RET",  # flake8-return
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "TCH", # flake8-type-checking
    "PTH",  # flake8-pathlib
    "PGH", # pygrep-hooks
    "PL", # Pylint
    "TRY", # tryceratops
    "RUF", # Ruff
]

lint.ignore = [
    "COM812",
    "ISC001",
    "B008",  # do not perform function calls in argument defaults
    "PTH123", # builtin-open
    "S101", "S311", # assert, pseudo-random
    "PLR2004",
    "PT023", # pytest-style
    "RUF012"
]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["id"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
asyncio_mode = "auto"